- name: Echo Test
  shell: echo "{{ lookup('env','MY_ENV') }}"

- name: Push configuration for beats
  tags: functionbeat
  template:
    src: "templates/functionbeat.yml.j2"
    dest: "/home/runner/work/ansible-stuff/ansible-stuff/roles/functionbeat/config/functionbeat.yml"
    mode: 0644