on: [push]
jobs:
 deploy-function-beat-play:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout public repo
      uses: actions/checkout@master
    - name: Create terraform cli config
      run: printf '%s\n' '#!/bin/bash' 'echo $ANSIBLE_VAULT_PASSWORD' > $HOME/vault_env  && chmod +x $HOME/vault_env
    - name: Print Workspace and Home
      run: echo $HOME && echo $WORKSPACE
    - name: Run Playbook
      run: ansible-playbook -vvv playbook.yml
      env:
        ANSIBLE_VAULT_PASSWORD_FILE: $HOME/vault_env
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}